deploy:
  release: export-monzo-transactions-$(APPVEYOR_REPO_BRANCH)-$(appveyor_build_version)
  description: 'Automated build from Appveyor'
  provider: GitHub
  auth_token:
    secure: GC/qNFcIIol2RWKn4/CsNEOt/8I7j9L40eOLpyJU+mqO1LnkiQrDxbA1bvUsWJhd
  artifact: /.*\.exe/
  draft: true
  prerelease: true
  on:
    branch: .*
    appveyor_repo_tag: true 
build_script:
  - cmd: go generate
  - cmd: go get
  - cmd: go build